# Compose file for local development
version: "3.6"

services:
  todo-api:
    image: todo-api
    container_name: todo-api
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
    - "8000:8000"
    volumes:
    - "./api:/app"
    environment:
    - MONGO_HOST=todo-mongodb
    - MONGO_USERNAME
    - MONGO_PASSWORD
  todo-mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: todo-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
    ports:
      - 27017:27017
    volumes:
      - todo-mongodb-container:/data/db
  todo-frontend:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
     - "3000:3000"
    volumes:
     - "./todo-frontend:/todo-frontend"
  
volumes:
      todo-mongodb-container: